const AUTHENTICATED_RW = [
  'create("users")',
  'read("users")',
  'update("users")',
  'delete("users")',
];

const PUBLIC_CREATE_INTERNAL_RW = [
  'create("any")',
  'read("users")',
  'update("users")',
  'delete("users")',
];

const SERVER_ONLY = [];

const INTERNAL_BUCKET_PERMISSIONS = [...AUTHENTICATED_RW];

const attr = {
  string: (key, size, required = false, options = {}) => ({
    key,
    type: "string",
    size,
    required,
    array: false,
    ...options,
  }),
  stringArray: (key, size, required = false, options = {}) => ({
    key,
    type: "string",
    size,
    required,
    array: true,
    ...options,
  }),
  email: (key, required = false, options = {}) => ({
    key,
    type: "email",
    required,
    array: false,
    ...options,
  }),
  enum: (key, elements, required = false, options = {}) => ({
    key,
    type: "enum",
    elements,
    required,
    array: false,
    ...options,
  }),
  float: (key, required = false, options = {}) => ({
    key,
    type: "float",
    required,
    array: false,
    ...options,
  }),
  integer: (key, required = false, options = {}) => ({
    key,
    type: "integer",
    required,
    array: false,
    ...options,
  }),
  boolean: (key, required = false, options = {}) => ({
    key,
    type: "boolean",
    required,
    array: false,
    ...options,
  }),
  datetime: (key, required = false, options = {}) => ({
    key,
    type: "datetime",
    required,
    array: false,
    ...options,
  }),
};

const keyIndex = (key, attributes, options = {}) => ({
  key,
  type: "key",
  attributes,
  orders: options.orders || attributes.map(() => "ASC"),
  lengths: options.lengths || [],
});

const uniqueIndex = (key, attributes, options = {}) => ({
  key,
  type: "unique",
  attributes,
  orders: options.orders || attributes.map(() => "ASC"),
  lengths: options.lengths || [],
});

export const APPWRITE_PRODUCTION_SCHEMA = {
  database: {
    id: process.env.APPWRITE_DATABASE_ID || "studio_manager",
    name: process.env.APPWRITE_DATABASE_NAME || "Studio Manager",
  },
  buckets: [
    {
      bucketId: "task-attachments",
      name: "Task Attachments",
      permissions: INTERNAL_BUCKET_PERMISSIONS,
      fileSecurity: false,
      enabled: true,
      maximumFileSize: 50 * 1024 * 1024,
      allowedFileExtensions: [
        "jpg",
        "jpeg",
        "png",
        "gif",
        "webp",
        "pdf",
        "doc",
        "docx",
        "txt",
        "zip",
        "rar",
      ],
      compression: "gzip",
      encryption: true,
      antivirus: true,
      transformations: true,
    },
  ],
  collections: [
    {
      collectionId: "profiles",
      name: "Profiles",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("user_id", 36, true),
        attr.string("full_name", 128, true),
        attr.email("email", true),
        attr.string("phone_number", 32),
        attr.string("street_address", 255),
        attr.string("city", 128),
        attr.string("state", 128),
        attr.string("zip_code", 32),
        attr.string("country", 128),
        attr.boolean("google_calendar_connected", false, { default: false }),
        attr.string("google_calendar_email", 255),
        attr.enum("google_calendar_sync_source", ["primary"]),
        attr.datetime("google_calendar_connected_at"),
      ],
      indexes: [
        uniqueIndex("profiles_user_id_unique", ["user_id"]),
        uniqueIndex("profiles_email_unique", ["email"]),
      ],
    },
    {
      collectionId: "google_calendar_connections",
      name: "Google Calendar Connections",
      permissions: SERVER_ONLY,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("user_id", 36, true),
        attr.string("provider_email", 255),
        attr.enum("sync_source", ["primary"], true),
        attr.datetime("connected_at", true),
        attr.string("refresh_token", 2048, true),
        attr.string("access_token", 4096),
        attr.datetime("access_token_expires_at"),
      ],
      indexes: [
        uniqueIndex("google_calendar_connections_user_unique", ["user_id"]),
      ],
    },
    {
      collectionId: "user_roles",
      name: "User Roles",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("user_id", 36, true),
        attr.enum("role", ["owner", "administrator", "team"], true),
        attr.string("assigned_by", 36),
      ],
      indexes: [uniqueIndex("user_roles_user_unique", ["user_id"])],
    },
    {
      collectionId: "team_members",
      name: "Team Members",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("user_id", 36, true),
        attr.string("name", 128, true),
        attr.string("position", 128, true),
        attr.datetime("start_date", true),
        attr.stringArray("skills", 128),
      ],
      indexes: [keyIndex("team_members_user_idx", ["user_id"])],
    },
    {
      collectionId: "invitations",
      name: "Invitations",
      permissions: PUBLIC_CREATE_INTERNAL_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.email("email", true),
        attr.enum("role", ["owner", "administrator", "team"], true),
        attr.string("invited_by", 36, true),
        attr.datetime("expires_at", true),
        attr.datetime("accepted_at"),
        attr.string("token", 64, true),
        attr.string("metadata", 2048),
      ],
      indexes: [
        uniqueIndex("invitations_token_unique", ["token"]),
        keyIndex("invitations_email_idx", ["email"]),
        keyIndex("invitations_expires_idx", ["expires_at"]),
        keyIndex("invitations_accepted_idx", ["accepted_at"]),
      ],
    },
    {
      collectionId: "clients",
      name: "Clients",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("user_id", 36, true),
        attr.string("name", 128, true),
        attr.email("email", true),
        attr.string("phone", 32),
        attr.string("address", 255),
        attr.enum("lead_source", ["Dribbble", "Website", "LinkedIn", "Behance", "Direct Email", "Other"], true),
      ],
      indexes: [
        keyIndex("clients_user_idx", ["user_id"]),
        keyIndex("clients_email_idx", ["email"]),
      ],
    },
    {
      collectionId: "projects",
      name: "Projects",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("user_id", 36, true),
        attr.string("name", 128, true),
        attr.string("client_id", 36, true),
        attr.enum("status", ["Planning", "In progress", "Awaiting Feedback", "Completed", "Paused", "Cancelled"], true),
        attr.datetime("deadline", true),
        attr.float("fee", true),
        attr.enum("currency", ["USD", "IDR"], true),
        attr.enum("project_type", ["Project Based", "Monthly Retainer", "Monthly Pay as you go"], true),
        attr.stringArray("categories", 128),
        attr.stringArray("team_members", 36),
      ],
      indexes: [
        keyIndex("projects_user_idx", ["user_id"]),
        keyIndex("projects_client_idx", ["client_id"]),
      ],
    },
    {
      collectionId: "payments",
      name: "Payments",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("user_id", 36),
        attr.string("project_id", 36, true),
        attr.enum("payment_type", ["Down Payment", "Final Payment", "Milestone Payment"], true),
        attr.float("amount", true),
        attr.datetime("date", true),
        attr.string("notes", 4096),
      ],
      indexes: [
        keyIndex("payments_user_idx", ["user_id"]),
        keyIndex("payments_project_idx", ["project_id"]),
      ],
    },
    {
      collectionId: "leads",
      name: "Leads",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("user_id", 36, true),
        attr.string("name", 128, true),
        attr.email("email", true),
        attr.string("phone", 32),
        attr.string("source", 128),
        attr.enum(
          "stage",
          [
            "Leads",
            "First Meeting",
            "Follow up 1",
            "Follow up 2",
            "Follow up 3",
            "Ghosting",
            "Provide Moodboard/Stylescape",
            "Down Payment",
            "Kickoff",
            "Finish",
          ],
          true
        ),
        attr.string("notes", 2048),
        attr.string("address", 255),
        attr.datetime("updated_at"),
      ],
      indexes: [
        keyIndex("leads_user_idx", ["user_id"]),
        keyIndex("leads_email_idx", ["email"]),
        keyIndex("leads_stage_idx", ["stage"]),
      ],
    },
    {
      collectionId: "invoices",
      name: "Invoices",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("user_id", 36, true),
        attr.string("invoice_number", 64, true),
        attr.string("client_id", 36, true),
        attr.datetime("date", true),
        attr.datetime("due_date", true),
        attr.string("payment_terms", 64, true),
        attr.float("subtotal", true),
        attr.float("tax_percentage", true),
        attr.float("tax_amount", true),
        attr.float("discount_percentage", true),
        attr.float("discount_amount", true),
        attr.float("total", true),
        attr.string("notes", 2048),
        attr.string("terms_and_conditions", 2048),
        attr.enum("status", ["Draft", "Sent", "Paid", "Overdue"], true),
        attr.enum("payment_type", ["Down Payment", "Final Payment", "Milestone Payment"]),
      ],
      indexes: [
        keyIndex("invoices_user_idx", ["user_id"]),
        keyIndex("invoices_client_idx", ["client_id"]),
        uniqueIndex("invoices_number_unique", ["invoice_number"]),
      ],
    },
    {
      collectionId: "invoice_items",
      name: "Invoice Items",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("invoice_id", 36, true),
        attr.string("user_id", 36, true),
        attr.string("description", 4096, true),
        attr.float("quantity", true),
        attr.float("rate", true),
        attr.float("amount", true),
      ],
      indexes: [
        keyIndex("invoice_items_invoice_idx", ["invoice_id"]),
        keyIndex("invoice_items_user_idx", ["user_id"]),
      ],
    },
    {
      collectionId: "tasks",
      name: "Tasks",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("project_id", 36, true),
        attr.string("user_id", 36, true),
        attr.string("title", 255, true),
        attr.string("description", 2048),
        attr.enum("status", ["Planning", "In progress", "Completed", "Paused", "Cancelled"], true),
        attr.datetime("due_date"),
        attr.enum("priority", ["Low", "Normal", "High", "Urgent"], true),
        attr.enum("task_type", ["Primary", "Secondary", "Tertiary"], true),
        attr.stringArray("assignees", 36),
        attr.string("parent_task_id", 36),
        attr.datetime("completed_at"),
        attr.string("brief_id", 36),
        attr.string("brief_type", 64),
      ],
      indexes: [
        keyIndex("tasks_project_idx", ["project_id"]),
        keyIndex("tasks_user_idx", ["user_id"]),
        keyIndex("tasks_parent_idx", ["parent_task_id"]),
        keyIndex("tasks_brief_idx", ["brief_id"]),
      ],
    },
    {
      collectionId: "task_comments",
      name: "Task Comments",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("task_id", 36, true),
        attr.string("user_id", 36, true),
        attr.string("content", 2048, true),
      ],
      indexes: [
        keyIndex("task_comments_task_idx", ["task_id"]),
        keyIndex("task_comments_user_idx", ["user_id"]),
      ],
    },
    {
      collectionId: "task_attachments",
      name: "Task Attachments",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("task_id", 36, true),
        attr.string("user_id", 36, true),
        attr.string("file_name", 255, true),
        attr.string("file_url", 2048, true),
        attr.integer("file_size", true),
        attr.string("file_type", 128, true),
      ],
      indexes: [
        keyIndex("task_attachments_task_idx", ["task_id"]),
        keyIndex("task_attachments_user_idx", ["user_id"]),
      ],
    },
    {
      collectionId: "task_activities",
      name: "Task Activities",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("task_id", 36, true),
        attr.string("user_id", 36, true),
        attr.enum(
          "activity_type",
          [
            "comment",
            "status_change",
            "assignee_change",
            "priority_change",
            "attachment",
            "task_created",
            "due_date_change",
            "task_updated",
            "brief_connected",
            "brief_disconnected",
          ],
          true
        ),
        attr.string("content", 2048),
        attr.string("metadata", 2048),
        attr.string("attachments", 16384),
      ],
      indexes: [
        keyIndex("task_activities_task_idx", ["task_id"]),
        keyIndex("task_activities_user_idx", ["user_id"]),
      ],
    },
    {
      collectionId: "notifications",
      name: "Notifications",
      permissions: AUTHENTICATED_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("user_id", 36, true),
        attr.string("type", 128, true),
        attr.string("title", 255, true),
        attr.string("message", 4096, true),
        attr.string("data", 2048),
        attr.datetime("read_at"),
      ],
      indexes: [
        keyIndex("notifications_user_idx", ["user_id"]),
        keyIndex("notifications_read_idx", ["read_at"]),
      ],
    },
    {
      collectionId: "graphic_design_briefs",
      name: "Graphic Design Briefs",
      permissions: PUBLIC_CREATE_INTERNAL_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("name", 128, true),
        attr.email("email", true),
        attr.string("company_name", 255, true),
        attr.string("status", 64, true),
        attr.string("brief_payload", 16384, true),
        attr.datetime("submission_date", true),
        attr.string("user_id", 36),
        attr.string("submitted_for_id", 36),
      ],
      indexes: [
        keyIndex("graphic_briefs_user_idx", ["user_id"]),
        keyIndex("graphic_briefs_email_idx", ["email"]),
      ],
    },
    {
      collectionId: "ui_design_briefs",
      name: "UI Design Briefs",
      permissions: PUBLIC_CREATE_INTERNAL_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("name", 128, true),
        attr.email("email", true),
        attr.string("company_name", 255, true),
        attr.string("status", 64, true),
        attr.string("brief_payload", 16384, true),
        attr.datetime("submission_date", true),
        attr.string("user_id", 36),
        attr.string("submitted_for_id", 36),
      ],
      indexes: [
        keyIndex("ui_briefs_user_idx", ["user_id"]),
        keyIndex("ui_briefs_email_idx", ["email"]),
      ],
    },
    {
      collectionId: "illustration_design_briefs",
      name: "Illustration Design Briefs",
      permissions: PUBLIC_CREATE_INTERNAL_RW,
      documentSecurity: false,
      enabled: true,
      attributes: [
        attr.string("name", 128, true),
        attr.email("email", true),
        attr.string("company_name", 255, true),
        attr.string("status", 64, true),
        attr.string("brief_payload", 16384, true),
        attr.datetime("submission_date", true),
        attr.string("user_id", 36),
        attr.string("submitted_for_id", 36),
      ],
      indexes: [
        keyIndex("illustration_briefs_user_idx", ["user_id"]),
        keyIndex("illustration_briefs_email_idx", ["email"]),
      ],
    },
  ],
};
