// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://eqpsztxrnysaaoqvdqow.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVxcHN6dHhybnlzYWFvcXZkcW93Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDEzMzMwMTIsImV4cCI6MjA1NjkwOTAxMn0.KUnGWxculKKX01nUjBfH4fd5J2VJJ1Zt2pRZelK2Dq0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);